;; //////////////////////////////////////////////////////////////////
;; File    : RelicCOH.module
;; Desc    : RelicCOH Mod descriptor file.
;; 
;; (c) 2008 Relic Entertainment Inc.
;; 

[global]

Parent = PhoenixMod
UIName = $1080
Description = Company of Heroes
DllName = WW2Mod
ModVersion = 1.0
LocFolder = DLC1\Locale
SpeechManagerCache = SpeechManagerDLC1.cache

[game]
PlayerDropBehavior = aitakeover

[movies:common]
folder = DLC1\Movies

[data:common]
folder = DLC1\Data
archive.01 = DLC1\Archives\DLC1Data

[data:art_low]
folder = DLC1\DataArtLow
archive.01 = DLC1\Archives\DLC1ArtLow

[data:art_high]
folder = DLC1\DataArtHigh
archive.01 = DLC1\Archives\DLC1ArtHigh

[locale:english]
folder.01 = DLC1\Locale\English

[data:english:01]
folder = DLC1\DataSoundEnglish
archive.01 = DLC1\Archives\DLC1SoundSpeechEnglish

[locale:german]

[data:german:01]
folder = DLC1\DataSoundGerman
archive.01 = DLC1\Archives\DLC1SoundSpeechGerman

[locale:french]

[data:french:01]
folder = DLC1\DataSoundFrench
archive.01 = DLC1\Archives\DLC1SoundSpeechFrench

[locale:spanish]

[data:spanish:01]
folder = DLC1\DataSoundSpanish
archive.01 = DLC1\Archives\DLC1SoundSpeechSpanish

[locale:russian]

[data:russian:01]
folder = DLC1\DataSoundRussian
archive.01 = DLC1\Archives\DLC1SoundSpeechRussian

[locale:italian]

[data:italian:01]
folder = DLC1\DataSoundEnglish
archive.01 = DLC1\Archives\DLC1SoundSpeechEnglish

[locale:czech]

[data:czech:01]
folder = DLC1\DataSoundEnglish
archive.01 = DLC1\Archives\DLC1SoundSpeechEnglish

[locale:polish]

[data:polish:01]
folder = DLC1\DataSoundEnglish
archive.01 = DLC1\Archives\DLC1SoundSpeechEnglish

[locale:chinesetrad]

[data:chinesetrad:01]
folder = DLC1\DataSoundEnglish
archive.01 = DLC1\Archives\DLC1SoundSpeechEnglish

[locale:japanese]

[data:japanese:01]
folder = DLC1\DataSoundEnglish
archive.01 = DLC1\Archives\DLC1SoundSpeechEnglish

[locale:korean]

[data:korean:01]
folder = DLC1\DataSoundEnglish
archive.01 = DLC1\Archives\DLC1SoundSpeechEnglish



