;; //////////////////////////////////////////////////////////////////
;; File    : RelicOps.module
;; Desc    : RelicOps Mod descriptor file.
;; 
;; (c) 2008 Relic Entertainment Inc.
;; 

[global]

Parent = PhoenixMod
UIName = $1080
Description = Company of Heroes
DllName = WW2Mod
ModVersion = 1.0

[game]
PlayerDropBehavior = kill

[preview:common]
folder = CoH\OPS\DataPreview

[attrib:ingame]
archive.01 = CoH\Ops\Archives\OPSAttribArchive

[data:common]
folder = CoH\Ops\Data
archive.01 = CoH\Ops\Archives\OPSData

[locale:chineseenglish]
folder.01 = CoH\Ops\Locale\ChineseEnglish

[locale:chinesetrad]
folder.01 = CoH\Ops\Locale\ChineseTrad

[locale:czech]
folder.01 = CoH\Ops\Locale\Czech

[locale:english]
folder.01 = CoH\Ops\Locale\English

[locale:french]
folder.01 = CoH\Ops\Locale\French

[locale:german]
folder.01 = CoH\Ops\Locale\German

[locale:italian]
folder.01 = CoH\Ops\Locale\Italian

[locale:japanese]
folder.01 = CoH\Ops\Locale\Japanese

[locale:korean]
folder.01 = CoH\Ops\Locale\Korean

[locale:polish]
folder.01 = CoH\Ops\Locale\Polish

[locale:russian]
folder.01 = CoH\Ops\Locale\Russian

[locale:spanish]
folder.01 = CoH\Ops\Locale\Spanish
